### ISSUE TITLE
import table_logger error version 0.3.6

### ISSUE THREAD

**Issue by shivamjadhav2000** [AleksTk/table-logger#10]
ttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20;

**Comment by AleksTk** [comment]
Fixed in https://github.com/AleksTk/table-logger/commit/73fe1bf96bcf958b6a8477bdcc77d379facee117
